#!/usr/bin/env bash
# Displays content of /etc/passwd file

passwd_file="/etc/passwd"

while IFS=: read -r username x userid x home _; do
    # Display username, user id, and home directory path
    echo "Username: $username"
    echo "User ID: $userid"
    echo "Home Directory: $home"
    echo "----------------------"
done < "$passwd_file"
