#!/usr/bin/env bash
# This displays Best School 10 times with Hi on the 9th line
a=0

while [ $a -lt 10 ]; do
    if [ $a -eq 8 ]; then
        echo -e "Best School\nHi"
    else
        echo "Best School"
    fi
    ((a++))
done

