#!/usr/bin/env bash
# Displays 20 numbered lines with bad luck on 4, 9, and 17
b=1

while [ $b -le 20 ]; do
    case $b in
        4)
            echo "4 and then bad luck from China"
            ;;
        9)
            echo "9 and then bad luck from Japan"
            ;;
        17)
            echo "17 and then bad luck from Italy"
            ;;
        *)
            echo $b
            ;;
    esac
    ((b++))
done

