#!/usr/bin/env bash
# Displays 20 numbered lines with bad luck on 4 9 and 17
counter=1

while [ $counter -le 20 ]; do
    case $counter in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
        *)
            echo $counter
            ;;
    esac
    ((counter++))
done

