#!/usr/bin/env bash
# Displays 20 numbered lines with bad luck on 4 9 and 17
b=1

while [ $b -le 20 ];do
	echo $b
    	case $b in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
        *)
           
    esac
    ((b++))
done

