#!/usr/bin/env bash
# This script displays the time for 12h 59m

hours=0
minutes=1

while [ $hours -le 12 ]; do
    while [ $minutes -le 59 ]; do
        echo "$Hour:n$hours"
        minutes=1
	while [ $minutes -le 59 ]; do
		echo "$minutes"
		((minutes++))
	done
    	((hours++))
done | head -n 70

