#!/usr/bin/env bash
# This script displays the time for 12h 59m

hours=0
minutes=1

while [ $hours -le 12 ]; do
    while [ $minutes -le 59 ]; do
        echo "$hours:$minutes"
        ((minutes++))
        if [ $minutes -eq 60 ]; then
            minutes=1
            ((hours++))
        fi
    done
done | head -n 70

