#!/usr/bin/env bash
# This script displays the time for 12h 59m
hours=0

while [ $hours -le 12 ]; do
    echo "Hour: $hours"
    minutes=1
    while [ $minutes -le 59 ]; do
        echo "$minutes"
        ((minutes++))
    done
    ((hours++))
done | head -n 70
